# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  sonarscanner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup JDK
      uses: actions/setup-java@v3.6.0
      with: 
        distribution: 'zulu'
        java-version: '11'
        java-package: jre
    
    # Runs a single command using the runners shell
    - name: check java version
      run: echo "java -version"
